# file: action.yml
# version: 1.1.0
# guid: 7b9e4f3a-6d2c-5e1a-8f9d-3c7e2a4b6d1f

name: "Release Protocol Buffers"
description: "Generate and release Protocol Buffer SDKs for multiple languages"
author: "jdfalk"

branding:
  icon: "code"
  color: "green"

inputs:
  buf-version:
    description: "Buf version to use"
    required: false
    default: "latest"
  proto-dir:
    description: "Directory containing .proto files"
    required: false
    default: "proto"
  buf-config:
    description: "Path to buf.yaml"
    required: false
    default: "buf.yaml"
  buf-gen-config:
    description: "Path to buf.gen.yaml"
    required: false
    default: "buf.gen.yaml"
  generate-sdks:
    description: "Whether to generate SDKs"
    required: false
    default: "true"
  sdk-languages:
    description: "SDK languages to generate (comma-separated: go,python,typescript)"
    required: false
    default: "go"
  output-dir:
    description: "Output directory for generated code"
    required: false
    default: "gen"
  run-lint:
    description: "Run buf lint"
    required: false
    default: "true"
  run-breaking:
    description: "Check for breaking changes"
    required: false
    default: "true"
  against-branch:
    description: "Branch to check breaking changes against"
    required: false
    default: "main"
  create-tags:
    description: "Create SDK-specific tags"
    required: false
    default: "true"
  tag-prefix:
    description: "Tag prefix for SDK releases"
    required: false
    default: "proto"
  github-token:
    description: "GitHub token for tagging"
    required: false
    default: ${{ github.token }}
  use-docker:
    description: "Run inside the prebuilt Docker image"
    required: false
    default: "false"
  docker-image:
    description: "Docker image reference (tag or digest) to use when use-docker is true"
    required: false
    default: "ghcr.io/jdfalk/release-protobuf-action:main"

outputs:
  generated-languages:
    description: "Languages that were generated"
    value: ${{ steps.generate.outputs.languages || steps.generate-docker.outputs.languages }}
  output-path:
    description: "Path to generated code"
    value: ${{ steps.generate.outputs.path || steps.generate-docker.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Generate SDKs (docker)
      id: generate-docker
      if: inputs.use-docker == 'true'
      shell: bash
      env:
        BUF_VERSION: ${{ inputs.buf-version }}
        PROTO_DIR: ${{ inputs.proto-dir }}
        BUF_CONFIG: ${{ inputs.buf-config }}
        BUF_GEN_CONFIG: ${{ inputs.buf-gen-config }}
        GENERATE_SDKS: ${{ inputs.generate-sdks }}
        SDK_LANGUAGES: ${{ inputs.sdk-languages }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        RUN_LINT: ${{ inputs.run-lint }}
        RUN_BREAKING: ${{ inputs.run-breaking }}
        AGAINST_BRANCH: ${{ inputs.against-branch }}
        CREATE_TAGS: ${{ inputs.create-tags }}
        TAG_PREFIX: ${{ inputs.tag-prefix }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DOCKER_IMAGE: ${{ inputs.docker-image }}
        GITHUB_OUTPUT: ${{ env.GITHUB_OUTPUT }}
        GITHUB_STEP_SUMMARY: ${{ env.GITHUB_STEP_SUMMARY }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        set -euo pipefail

        if ! command -v docker >/dev/null 2>&1; then
          echo "::error::Docker is required when use-docker is true."
          exit 1
        fi

        touch "$GITHUB_OUTPUT" "$GITHUB_STEP_SUMMARY"

        if ! docker pull "$DOCKER_IMAGE"; then
          echo "::warning::Pull failed, building $DOCKER_IMAGE locally."
          docker build --tag "$DOCKER_IMAGE" "${{ github.action_path }}"
        fi

        docker run --rm \
          -e BUF_VERSION \
          -e PROTO_DIR \
          -e BUF_CONFIG \
          -e BUF_GEN_CONFIG \
          -e GENERATE_SDKS \
          -e SDK_LANGUAGES \
          -e OUTPUT_DIR \
          -e RUN_LINT \
          -e RUN_BREAKING \
          -e AGAINST_BRANCH \
          -e CREATE_TAGS \
          -e TAG_PREFIX \
          -e GITHUB_TOKEN \
          -e GITHUB_OUTPUT \
          -e GITHUB_STEP_SUMMARY \
          -e GITHUB_REF \
          -v "$GITHUB_OUTPUT:$GITHUB_OUTPUT" \
          -v "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          -v "${{ github.workspace }}:/repo" \
          -w /repo \
          "$DOCKER_IMAGE"

    - name: Set up Buf
      if: inputs.use-docker != 'true'
      uses: bufbuild/buf-setup-action@v1
      with:
        version: ${{ inputs.buf-version }}
        github_token: ${{ inputs.github-token }}

    - name: Verify configuration
      if: inputs.use-docker != 'true'
      run: |
        if [ ! -f "${{ inputs.buf-config }}" ]; then
          echo "Error: buf.yaml not found at ${{ inputs.buf-config }}"
          exit 1
        fi

        if [ "${{ inputs.generate-sdks }}" = "true" ] && [ ! -f "${{ inputs.buf-gen-config }}" ]; then
          echo "Error: buf.gen.yaml not found at ${{ inputs.buf-gen-config }}"
          exit 1
        fi
      shell: bash

    - name: Run buf lint
      if: inputs.use-docker != 'true' && inputs.run-lint == 'true'
      run: |
        buf lint --config ${{ inputs.buf-config }}
      shell: bash

    - name: Check breaking changes
      if: inputs.use-docker != 'true' && inputs.run-breaking == 'true'
      run: |
        buf breaking --against ".git#branch=${{ inputs.against-branch }}" --config ${{ inputs.buf-config }} || true
      shell: bash

    - name: Generate code
      id: generate
      if: inputs.use-docker != 'true' && inputs.generate-sdks == 'true'
      run: |
        mkdir -p ${{ inputs.output-dir }}
        buf generate --config ${{ inputs.buf-gen-config }}
        echo "languages=${{ inputs.sdk-languages }}" >> $GITHUB_OUTPUT
        echo "path=${{ inputs.output-dir }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create SDK tags
      if: inputs.use-docker != 'true' && inputs.create-tags == 'true' && github.ref_type == 'tag'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        BASE_TAG="${GITHUB_REF#refs/tags/}"
        IFS=',' read -ra LANGS <<< "${{ inputs.sdk-languages }}"

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        for lang in "${LANGS[@]}"; do
          SDK_TAG="${{ inputs.tag-prefix }}/${lang}/${BASE_TAG}"
          git tag -a "$SDK_TAG" -m "Protocol Buffer SDK release for ${lang}: ${BASE_TAG}"
          git push origin "$SDK_TAG"
          echo "Created tag: $SDK_TAG"
        done
      shell: bash

    - name: Output summary
      run: |
        echo "## Protocol Buffer Release Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Proto Directory:** ${{ inputs.proto-dir }}" >> $GITHUB_STEP_SUMMARY
        echo "**SDK Languages:** ${{ inputs.sdk-languages }}" >> $GITHUB_STEP_SUMMARY
        echo "**Output Directory:** ${{ inputs.output-dir }}" >> $GITHUB_STEP_SUMMARY
      shell: bash
